version: "3.9"

services:
  flask_app:
    container_name: flask_app_jru
    image: francescoxx/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
    volumes:
    - OUTPUT_FILES:/home/output_files/
  flask_db:
    container_name: flask_db_jru
    image: postgres:12
    ports:
      - "6969:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data2

volumes:
  pgdata: {}
  output_files: {}
    